{% set name = "dranspose" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32271c83067438726755f87430feb783f2eaacae80f52eb4312ca730434905af

build:
  entry_points:
    - dranspose = dranspose.cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pyzmq
    - redis-py
    - fastapi
    - uvicorn
    - numpy
    - pydantic
    - pydantic-settings
    - cbor2
    - redis-logs
    - h5py

test:
  imports:
    - dranspose
  commands:
    - pip check
    - dranspose --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://dranspo.se/
  summary: A stream matrix transposition framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felix-engelmann
